name 'tfc_agent'
maintainer 'Michael Tharpe'
maintainer_email 'mtharpe@noemail.not'
license 'Apache-2.0'
description 'Installs/Configures tfc_agent'
version '0.1.0'
chef_version '>= 15.0'

issues_url 'https://github.com/mtharpe/chef-terraform-cloud-agent-recipe/issues'
source_url 'https://github.com/mtharpe/chef-terraform-cloud-agent-recipe'

supports 'ubuntu', '<= 18.0'
supports 'centos', '<= 7.0'
supports 'redhat', '<= 7.0'
supports 'fedora', '<= 32.0'
